spring.application.name=VoteZy
spring.datasource.url=jdbc:mysql://localhost:3306/votezy_db
spring.datasource.username=root
spring.datasource.password=root@2005root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect